### ISSUE TITLE
Issues on Windows 11     error: MitsubaImporter.dll is not a shared library

### ISSUE THREAD

**Issue by chenbixuan2017** [ssteinberg/PLTFalcor#3]
Hello!
Thanks for posting such amazing work!
I am interested in this project and am trying to use it for trial, but got stuck in the initial step "Building/Configure Presets"
when I was trying to use the instruction "cmake --build build/windows-vs2019", the error below came.

 ImportError: Failed to load plugin library from E:\PLTFalcor\build\windows-vs2019\bin\Debug\plugins\MitsubaImporter.d
  ll. File is not a shared library.
Stacktrace:
   0# 0x0000004dd11ec8b0 ( ?? )
   1# 0x00007ffed800be60 (RtlGetCurrentServiceSessionId)

I am sure I have met all the conditions mentioned in your prerequisites except for the operation system (mine is Windows 11)
Have you tested your work on Windows 11? If so, could you let me know how to solve the above problem?
Thanks in advance.

**Comment by ssteinberg** [comment]
mitsuba2 is a dependency. You can find precompiled release binaries in external/mitsuba)/bin/.

**Comment by rongduo** [comment]
@chenbixuan2017 Hi, have you resolved this issue? I met the same issue...

**Comment by udemegane** [comment]
I have encountered this problem too. It happens when PLTFalcor is a debug build, and the Mitsuba Importer depends on several other dlls, including TBB. The problem is that for some reason the MitsubaImporter.dll in the Debug build requires tbb.dll for release builds, not tbb_debug.dll. (I don't understand why this is)
In my environment, copying tbb.dll from bin/Release/ to bin/Debug/ in the build directory solved this error.
