### ISSUE TITLE
Issues running setup

### ISSUE THREAD

**Issue by M-Gjerde** [ssteinberg/PLTFalcor#6]
Hi
I'm having trouble testing your PLTFalcor framework. I can successfully build the [Falcor project](https://github.com/NVIDIAGameWorks/Falcor) from nvidia on my Ubuntu 22.04.
Running the setup.sh (Ubuntu 22.04) on a clean install returns the error pasted below. 

`./setup.sh 
Updating git submodules ...
Synchronizing submodule url for 'external/args'
Synchronizing submodule url for 'external/fmt'
Synchronizing submodule url for 'external/glfw'
Synchronizing submodule url for 'external/glm'
Synchronizing submodule url for 'external/imgui'
Synchronizing submodule url for 'external/pybind11'
Synchronizing submodule url for 'external/vulkan-headers'
Fetching dependencies ...
Package 'python' at version '3.7.9-180.74b501b5-linux-x86_64' is missing from local storage.
packman(ERROR): Unable to download file from 'https://d4i3qtqj3r0z5.cloudfront.net/python%403.7.9-180.74b501b5-linux-x86_64' (server returned 403)
Failed to fetch dependencies!
`

Do you now how to solve this? I am not familiar with pacman as a package/dependency manager.

**Comment by ssteinberg** [comment]
You can try to update the python version to the one from the up-to-date Falcor.

**Comment by GuangyanCai** [comment]
I also have the same problem, but after fixing the python version there are other dependencies that are not found. The problem is actually that packman is outdated, which is reported in [another issue](https://github.com/NVIDIAGameWorks/Falcor/issues/411#issuecomment-1891535996). Copying the `tools/packman` directory from the official Falcor repo works with a clean clone.
